services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: template
      POSTGRES_USER: template
      POSTGRES_PASSWORD: template
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
